/*
 * File: ProgramHierarchy.java
 * Name: 
 * Section Leader: 
 * ---------------------------
 * This file is the starter file for the ProgramHierarchy problem.
 */

import acm.graphics.*;
import acm.program.*;
import java.awt.*;

public class ProgramHierarchy extends GraphicsProgram {
	public static final int APPLICATION_HEIGHT= 1000;
	public static final int APPLICATION_WIDTH=1000;
	public static final int BOX_HEIGHT = 100;
	public static final int BOX_WIDTH = 200;
	
	public void run() {
		/* You fill this in. */
		add(new GRect(APPLICATION_WIDTH/2-BOX_WIDTH/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2, BOX_WIDTH, BOX_HEIGHT));
		add(new GRect(APPLICATION_WIDTH/2-BOX_WIDTH/2-BOX_WIDTH*5/4, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+2*BOX_HEIGHT, BOX_WIDTH, BOX_HEIGHT));
		add(new GRect(APPLICATION_WIDTH/2-BOX_WIDTH/2+BOX_WIDTH*5/4, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+2*BOX_HEIGHT, BOX_WIDTH, BOX_HEIGHT));
		add(new GRect(APPLICATION_WIDTH/2-BOX_WIDTH/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+2*BOX_HEIGHT, BOX_WIDTH, BOX_HEIGHT));
		add(new GLine(APPLICATION_WIDTH/2-BOX_WIDTH/2+BOX_WIDTH/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+BOX_HEIGHT, APPLICATION_WIDTH/2-BOX_WIDTH/2-BOX_WIDTH*5/4+BOX_WIDTH/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+2*BOX_HEIGHT));
		add(new GLine(APPLICATION_WIDTH/2-BOX_WIDTH/2+BOX_WIDTH/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+BOX_HEIGHT, APPLICATION_WIDTH/2-BOX_WIDTH/2-BOX_WIDTH*5/4+BOX_WIDTH*5/4+BOX_WIDTH/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+2*BOX_HEIGHT));
		add(new GLine(APPLICATION_WIDTH/2-BOX_WIDTH/2+BOX_WIDTH/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+BOX_HEIGHT, APPLICATION_WIDTH/2-BOX_WIDTH/2-BOX_WIDTH*5/4+BOX_WIDTH*10/4+BOX_WIDTH/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+2*BOX_HEIGHT));
		double asc1 = new GLabel("PROGRAM").getAscent();
		double dist1 = new GLabel("PROGAM").getWidth();
		add(new GLabel("PROGRAM", APPLICATION_WIDTH/2-BOX_WIDTH/2+(BOX_WIDTH-dist1)/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+BOX_HEIGHT/2+asc1/2));
		double asc2 = new GLabel("GRAPHICS PROGRAM").getAscent();
		double dist2 = new GLabel("GRAPHICS PROGAM").getWidth();
		add(new GLabel("GRAPHICS PROGRAM", APPLICATION_WIDTH/2-BOX_WIDTH/2-BOX_WIDTH*5/4+(BOX_WIDTH-dist2)/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+2*BOX_HEIGHT+BOX_HEIGHT/2+asc2/2));
		double asc3 = new GLabel("Cosole Program").getAscent();
		double dist3 = new GLabel("CONSOLE PROGRAM").getWidth();
		add(new GLabel("CONSOLE PROGRAM", APPLICATION_WIDTH/2-BOX_WIDTH/2+BOX_WIDTH*5/4+(BOX_WIDTH-dist3)/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+2*BOX_HEIGHT+BOX_HEIGHT/2+asc3/2));
		double dist4 = new GLabel("DIALOG PROGRAM").getWidth();
		add(new GLabel("DIALOG PROGRAM", APPLICATION_WIDTH/2-BOX_WIDTH/2+(BOX_WIDTH-dist4)/2, APPLICATION_HEIGHT/4-BOX_HEIGHT/2+2*BOX_HEIGHT+BOX_HEIGHT/2+asc3/2));
		
	}
}

